@startuml
skinparam svgTextStyle plain
skinparam nodesep 70
skinparam ranksep 100
skinparam linetype ortho
top to bottom direction



'------------------------------------------CLASSI/INTERFACCE------------------------------------------

+interface Mappabile<K, V> {
+esisteChiave(chiave: K): boolean
+ottieni(chiave: K): V
}


+class Biblioteca {
-libri: Libri {readOnly}
-utenti: Utenti {readOnly}
-prestiti: Prestiti {readOnly}

+Biblioteca()

+getPrestiti(): Prestiti
+getLibri(): Libri
+getUtenti(): Utenti

+salvaBibliotecaOBJ(nomeFile: String): void
+leggiBibliotecaOBJ(nomeFile: String): Biblioteca {static}
}


+interface Archiviabile<E> {
+aggiungi(elemento: E): void
+modifica(originale: E, modificato: E): void
+rimuovi(elemento: E): void
}


+class Utenti {
-chiaviMatricole: Map<Matricola, Utente> {readOnly}
-utenti: List<Utente> {readOnly}

+Utenti()

+getListaUtenti(): List<Utente>

+ricercaUtenti(input: String): List<Utente> 
}


+class Libri {
-chiaviISBN: Map<ISBN, Libro> {readOnly}
-libri: List<Libro> {readOnly}

+Libri()

+getListaLibri(): List<Libro>

+ricercaLibri(input: String): List<Libro> 
}


+class Prestiti {
-prestiti: List<Prestito> {readOnly}

+Prestiti()

+getListaPrestiti(): List<Prestito>

+filtra(filtro: Filtro): List<Prestito>
}


+class Utente {
-matricolaUtente: Matricola {readOnly}
-email: String
-prestitiAttivi: List<Prestito> [0...3] {readOnly}

+Utente(nome: String, cognome: String, matricolaUtente: Matricola, email: String)

+getMatricolaUtente(): Matricola
+getEmail(): String
+getPrestitiAttivi(): List<Prestito>

+setEmail(email: String): void

+aggiungiPrestito(prestito: Prestito): void
+rimuoviPrestito(prestito: Prestito): void
+verificaEmail(email: String): boolean {static} 
+verificaUtente(nome: String, cognome: String, matricolaUtente: String, email: String): boolean {static}
+hashCode(): int
+equals(o: Object): boolean
+compareTo(u: Persona): int
}


+class Libro {
-titolo: String 
-autori: List<Autore> {readOnly}
-annoPubblicazione: int 
-codiceISBNLibro: ISBN {readOnly}
-copieDisponibili: int 

+Libro(titolo: String, annoPubblicazione: int, codiceISBNLibro: ISBN, copieDisponibili: int, autori: String)

+getTitolo(): String
+getAnnoPubblicazione(): int
+getCodiceISBNLibro(): ISBN
+getCopieDisponibili(): int
+getAutori(): List<Autore>
+getStringaAutori(): String

+setTitolo(titolo: String): void
+setAnnoPubblicazione(annoPubblicazione: int): void
+setCopieDisponibili(copieDisponibili: int): void

+aggiungiAutore(autore: Autore): void
+rimuoviAutore(autore: Autore): void
-StringAutoriToList(autori: String): List<Autore> {static}
-ListAutoriToString(autori: List<Autore>): String {static}
+verificaLibro(autori: String, titolo: String, annoPubblicazione: String, codiceISBNLibro: String, copieDisponibili: String): boolean {static}
+hashCode(): int
+equals(o: Object): boolean
+compareTo(l: Libro): int
}


+class Prestito {
-matricolaUtente: Matricola {readOnly}
-codiceISBNLibro: ISBN {readOnly}
-dataInizio: LocalDate {readOnly}
-dataScadenza: LocalDate 
-dataRestituzione : LocalDate

+Prestito(matricolaUtente: Matricola, codiceISBNLibro: ISBN, dataInizio: LocalDate, dataScadenza: LocalDate)

+getMatricolaUtente(): Matricola
+getCodiceISBNLibro(): ISBN
+getDataInizio(): LocalDate 
+getDataScadenza(): LocalDate
+getDataRestituzione(): LocalDate 

+setDataScadenza(dataScadenza: LocalDate): void
+setDataRestituzione(dataRestituzione: LocalDate): void

+isAttivo(): boolean
-StringDataScadenzaToLocalDate(dataScadenza: String): LocalDate {static}
+verificaDataScadenza(dataScadenza: String): boolean {static}
+compareTo(p: Prestito): int
+toString(): String
}


+abstract class Persona {
-nome: String
-cognome: String 

+Persona(nome: String, cognome: String)

+getNome(): String
+getCognome(): String

+setNome(nome: String): void 
+setCognome(cognome: String): void 

+verificaNome(nome: String): boolean {static}
+verificaCognome(cognome: String): boolean {static}
+equals(o: Object): boolean
+compareTo(p: Persona): int
+toString(): String
}


+class Autore {
+Autore(nome: String, cognome: String)
}


+class Matricola {
-matricola: String {readOnly}

+Matricola(matricola: String)

+getMatricola(): String

+verificaMatricola(matricola: String): boolean {static}
+hashCode(): int
+equals(o: Object): boolean
+compareTo(m: Matricola): int
}


+class ISBN {
-codiceISBN: String {readOnly}

+ISBN(codiceISBN: String)

+getCodiceISBN(): String

+verificaISBN(codiceISBN: String): boolean {static}
-verificaISBN13(codiceISBN: String): boolean {static}
-verificaISBN10(codiceISBN: String): boolean {static}
+hashCode(): int
+equals(o: Object): boolean
+compareTo(i: ISBN): int
}

+enum Filtro {
TUTTI
ATTIVI
CONCLUSI
}




'------------------------------------------LAYOUT------------------------------------------

Biblioteca -[hidden]-> Archiviabile

Archiviabile -[hidden]> Mappabile


Mappabile -[hidden]-> Libri
Mappabile -[hidden]-> Utenti

Prestiti -[hidden]> Utenti
Utenti -[hidden]> Libri

Utente -[hidden]> Libro

Prestito -[hidden]-> Matricola
Matricola -[hidden]-> ISBN

Filtro -[hidden]> Prestiti




'------------------------------------------RELAZIONI------------------------------------------


Biblioteca "1" *--- "1" Utenti
Biblioteca "1" *-- "1" Libri
Biblioteca "1" *-- "1" Prestiti 

Utenti "1" *-- "0...*" Utente
Libri "1" *-- "0...*" Libro
Prestiti "1" *-- "0...*" Prestito

Libro "1" *-- "1...*" Autore

Prestito "0...3" <- "1" Utente

Utente -|> Persona
Autore -down-|> Persona

Libro "1" -down-> "1" ISBN
Prestito "1" -down-> "1" ISBN

Utente "1" --> "1" Matricola
Prestito "1" --> "1" Matricola

Mappabile <|.down. Utenti
Mappabile <|.down. Libri

Archiviabile <|... Prestiti
Archiviabile <|... Utenti
Archiviabile <|... Libri




@enduml