@startuml
skinparam nodesep 100
skinparam ranksep 150
skinparam linetype ortho
'skinparam linetype polyline
top to bottom direction



'------------------------------------------CLASSI/INTERFACCE------------------------------------------

interface GestioneConChiave<K, V> {
+esisteChiave(chiave: K): boolean
+ottieni(chiave: K): V
}


class Biblioteca {
-gestoreLibri: GestoreLibri {readOnly}
-gestoreUtenti: GestoreUtenti {readOnly}
-gestorePrestiti: GestorePrestiti {readOnly}

+Biblioteca()
+salvaBiblioteca(nomeFile: String): void
+leggiBiblioteca(nomeFile: String): Biblioteca {static}
}


interface GestioneArchivio<E> {
+aggiungi(elemento: E): void
+modifica(elemento: E): void
+rimuovi(elemento: E): void
}


class GestoreUtenti {
-matricole: Map<Matricola, Utente> {readOnly}
-utenti: List<Utente> {readOnly}

+GestoreUtenti()
+getUtenti(): List<Utente>
+ricerca(input: String): List<Utente> 
}


class GestoreLibri {
-ISBN: Map<ISBN, Libro> {readOnly}
-libri: List<Libro> {readOnly}

+GestoreLibri()
+getLibri(): List<Libro>
+ricerca(input: String): List<Libro> 
}


class GestorePrestiti {
-prestiti: List<Prestito> {readOnly}

+GestorePrestiti()
+getPrestiti(): List<Prestito>
}


class Utente {
-matricola: Matricola {readOnly}
-email: String
-prestitiAttivi: List<Prestito> [0...3] {readOnly}

+Utente(nome: String, cognome: String, matricola: Matricola, email: String)
+setEmail(email: String): void
+getEmail(): String
+getPrestitiAttivi(): List<Prestito>
+aggiungiPrestito(prestito: Prestito): void
+rimuoviPrestito(prestito: Prestito): void
+verificaUtente(nome: String, cognome: String, matricola: Matricola, email: String): boolean {static}
+verificaEmail(email: String): boolean {static} 
+equals(o: Object): boolean
+hashCode(): int
}


class Libro {
-titolo: String
-autori: List<Autore> {readOnly}
-annoPubblicazione: int 
-id: ISBN {readOnly}
-copieDisponibili: int 

+Libro(titolo: String, annoPubblicazione: int, id: ISBN, copieDisponibili: int)
+setTitolo(titolo: String): void
+getTitolo(): String
+getAutori(): List<Autore>
+aggiungiAutore(autore: Autore): void
+setAnnoPubblicazione(annoPubblicazione: int): void
+getAnnoPubblicazione(): int
+setCopieDisponibili(copieDisponibili: int): void
+getCopieDisponibili(): int
+verificaLibro(titolo: String, autori: List<Autore>, annoPubblicazione: int,
 id: ISBN, copieDisponibili: int): boolean (static)
+equals(o: Object): boolean
+hashCode(): int
}


class Prestito {
-matricola: Matricola {readOnly}
-id: ISBN {readOnly}
-dataInizio: LocalDate {readOnly}
-dataScadenza: LocalDate 
-dataRestituzione : LocalDate 

+Prestito(matricola: Matricola, id: ISBN, dataInizio: LocalDate,
dataScadenza: LocalDate, dataRestituzione LocalDate)
+setDataScadenza(data: LocalDate): void
+getDataScadenza(): LocalDate
+getDataInizio(): LocalDate 
+setDataRestituzione(data: LocalDate): void
+getDataRestituzione(): LocalDate 
+isAttivo(): boolean
+verificaPrestito(): boolean {static}
}


abstract class Persona {
-nome: String
-cognome: String 

+Persona(nome: String, cognome: String)
+setNome(nome: String): void 
+setCognome(cognome: String): void 
+getNome(): String
+getCognome(): String
+verificaNome(): boolean {static}
+verificaCognome(): boolean {static}
}


class Autore {

}


class Matricola {
-matricola: String {readOnly}

+Matricola(matricola: String)
+getMatricola(): String
+verificaMatricola(): boolean {static}
}


class ISBN {
-ISBN: String {readOnly}

+ISBN(ISBN: String)
+getISBN(): String
+verificaISBN(): boolean {static}
}


class Maschera {
-lunghezza: int {readOnly}
-maschera: String

+Maschera(lunghezza: int)
+getMaschera(): String
+setMaschera(maschera: String): void
+getLunghezza(): int
}


interface Filtrabile<E> {
+filtra(tipo: TipoFiltro): List<E>
}


enum TipoFiltro {
TUTTI
ATTIVI
CONCLUSI
}




'------------------------------------------LAYOUT------------------------------------------

Biblioteca -[hidden]-> GestioneArchivio
Biblioteca -[hidden]-> GestioneConChiave

GestioneArchivio -[hidden]> GestioneConChiave

GestioneConChiave -[hidden]-> GestoreLibri
GestioneConChiave -[hidden]-> GestoreUtenti

GestorePrestiti -[hidden]> GestoreUtenti
GestoreUtenti -[hidden]> GestoreLibri

Utente -[hidden]> Libro

Prestito -[hidden]-> Matricola
Matricola -[hidden]-> ISBN

Biblioteca --[hidden]> Maschera




'------------------------------------------RELAZIONI------------------------------------------

Biblioteca "1" *--- "1" GestoreUtenti
Biblioteca "1" *-- "1" GestoreLibri
Biblioteca "1" *-- "1" GestorePrestiti

GestoreUtenti "1" *-- "0...*" Utente
GestoreLibri "1" *-- "0...*" Libro
GestorePrestiti "1" *-- "0...*" Prestito

Libro "1" *-- "1...*" Autore

Prestito "1...3" -> "1" Utente

Utente -|> Persona
Autore -down-|> Persona

Libro <-down- ISBN
Prestito <-down- ISBN

Utente <-- Matricola
Prestito <-- Matricola

GestioneConChiave <|.down. GestoreUtenti
GestioneConChiave <|.down. GestoreLibri

GestioneArchivio <|... GestorePrestiti
GestioneArchivio <|... GestoreUtenti
GestioneArchivio <|... GestoreLibri

GestorePrestiti .up.|> Filtrabile 

Filtrabile -[hidden]-> TipoFiltro

@enduml