@startuml
left to right direction

package java{
	class Main
		
	package models{
		
		class Biblioteca
		class Matricola
		class ISBN
		abstract Persona
		exception OggettoGiaPresenteException
		exception FormatoCampiErratoException
		
		
		package prestiti{
			class Prestiti
			class Prestito
		}
			
		package libri{
			class Autore
			class Libri
			class Libro
			exception LibroGiaPresenteException
		}
			
		package utenti{
			class Utente
			class Utenti
			exception UtenteGiaPresenteException
		}

		package servizi{
			interface Archiviabile
			enum Filtro
			interface Mappabile
			class Maschera
		}
		
	}
	
}


@enduml