@startuml
left to right direction

package java{
	class Main
	
	package controllers{
		
		class BaseController
		class MenuController
		class RimozioneController
		
		package libri{
			class AggiuntaLibroController
			class LibriController
			class ModificaLibroController
		}
		
		package prestiti{
			class EstensionePrestitoController
			class PrestitiController
			class RegistazionePrestitoController
		}
		
		package utenti{
			class AggiuntaUtenteController
			class UtentiController
			class ModificaUtenteController
		}
	
	}
	
	package models{
		
		class Biblioteca
		class Matricola
		class ISBN
		abstract Persona
		exception FormatoCampiErratoException
		exception OggettoGiaPresenteException
		
		package libri{
			class Autore
			class Libri
			class Libro
			exception LibroGiaPresenteException
		}
		
		package prestiti{
			class Prestiti
			class Prestito
		}
		
		package utenti{
			class Utente
			class Utenti
			exception UtenteGiaPresenteException
		}
		
		package servizi{
			interface Archiviabile
			enum Filtro
			interface Mappabile
			class Maschera
		}
	}
	
	package resources{
		package views{
		
			class AvvisoConfermaRimozioneView
			class MenuView
			
			package libri{
				class LibriView
				class AggiuntaLibroView
				class ModificaLibroView
			}
			
			package prestiti{
				class EstensionePrestitoView
				class PrestitiView
				class RegistrazionePrestitoView
			}
			
			package utenti{
				class AggiuntaUtenteView
				class ModificaUtenteView
				class UtentiView
			}
		}
	}
}
'Models -[hidden]> Controllers


@enduml