@startuml

	actor Amministratore as a
	participant LibriController as cvl
	participant Libri as gl
	
	cvl->cvl: initialize(...)
	a->cvl: Apre schermata libri
	a->cvl: Seleziona la barra di ricerca
	
	'Ogni volta che viene inserito un carattere viene aggiornata la ricerca
	loop Inserimento sottostringa 
		a->cvl: Digita una sottostringa nella barra di ricerca
		cvl->gl: ricercaLibri(...)
		activate cvl
			activate gl
				gl->gl: Ricerca libri
				gl-->cvl:Restituisce libri che rispettano i criteri di ricerca
			deactivate gl
			cvl-->a: Mostra i libri che rispettano i criterii di ricerca
		deactivate cvl
		
		'Condizione di uscita dal loop
		break Seleziona un libro 
			a->cvl: clicca su un libro
		end

	end

@enduml