@startuml

	actor Amministratore as a
	participant UtentiController as cvu
	participant Utenti as gu

	
	cvu->cvu: initialize(...)
	a->cvu: Apre schermata utenti
	a->cvu: Seleziona la barra di ricerca
	
	'Ogni volta che viene inserito un carattere viene aggiornata la ricerca
	loop Inserimento sottostringa 
		a->cvu: Digita una sottostringa nella barra di ricerca
		cvu->gu: ricerca(...)
		activate gu
			gu->gu: Ricerca utenti
			gu-->a:Restituisce utenti che rispettano i criteri di ricerca
		deactivate gu
		
		'Condizione di uscita dal loop
		break Seleziona un utente 
			a->cvu: clicca su un utente
		end

	end



@enduml